app/views/assignments/index.haml
Closes #10.
Still can't decide if it's worth writing view specs for this app.
=> Demarcate start and end of assignments with arrows

app/models/user.rb
Had some trouble creating a user locally. Turned out that the validation
wording wasn't quite right.
=> Correcting validation wording

README.md
=> Add CodeClimate issue badge to README

app/models/assignment.rb, spec/models/assignment_spec.rb
=> Assignment.upcoming accounts for switchover hour

.travis.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
And fix the email notification settings
=> Upgrade CodeClimate test reporter

app/models/membership.rb, app/models/roster.rb, app/models/user.rb, db/migrate/20170417170635_drop_rosters_users.rb, db/migrate/20170417171136_create_memberships.rb, db/schema.rb
First steps towards doing #35.
=> Move from HABTM to has_many through

app/models/user.rb, app/views/layouts/_links.haml, db/seeds.rb, spec/factories/memberships.rb, spec/models/user_spec.rb
More progress on #35.
Next steps: locking down doing things to assignments.
As admin in current roster:
As admin, but in another roster:
As non-admin:
=> Use admin status to determine navbar links

lib/tasks/roster_migration.rake
`RAILS_ENV=production bundle exec rake migrations:rosters`
If we run this task after deploying, then we should be good to go.
=> Production data migration

app/views/users/edit.haml, app/views/users/new.haml
=> Add placeholder text for phone and SPIRE

app/controllers/rosters_controller.rb, app/models/user.rb, app/views/rosters/index.haml, spec/controllers/rosters_controller_spec.rb, spec/spec_helper.rb
=> Admins can only edit their own rosters

app/controllers/application_controller.rb, app/controllers/assignments_controller.rb, app/controllers/rosters_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.haml, app/views/users/index.haml, coverage/.last_run.json, spec/controllers/assignments_controller_spec.rb, spec/controllers/rosters_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb
=> Implement access control

app/controllers/assignments_controller.rb, app/mailers/assignments_mailer.rb, app/models/assignment.rb, app/views/assignments_mailer/changed_assignment.text.erb, app/views/assignments_mailer/deleted_assignment.text.erb, app/views/assignments_mailer/new_assignment.text.erb, coverage/.last_run.json, spec/controllers/assignments_controller_spec.rb, spec/factories/users.rb, spec/mailers/assignments_mailer_spec.rb, spec/models/assignment_spec.rb
Addresses #33.
After merging this (functionality), will work on configurability.
=> Notify when an assignment is created, changed, or destroyed

.rubocop.yml, app/assets/stylesheets/users/edit.scss, app/controllers/assignments_controller.rb, app/controllers/users_controller.rb, app/models/assignment.rb, app/views/users/edit.haml, db/migrate/20170425165219_add_change_notifications_enabled_to_users.rb, db/schema.rb, spec/controllers/assignments_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/assignment_spec.rb
=> Allow changing your notification settings

app/views/assignments/index.haml
=> [ci skip] Show current month in calendar

app/controllers/assignments_controller.rb, spec/controllers/assignments_controller_spec.rb
=> Starting user must be in rotation

app/assets/stylesheets/rosters/setup.scss, app/controllers/rosters_controller.rb, app/models/roster.rb, app/views/rosters/index.haml, app/views/rosters/setup.haml, config/routes.rb, spec/models/roster_spec.rb
I configured the IT number for #82, but I thought it might be good to
have a copy-and-paste friendly set of instructions for setting up a
particular roster's phone number (including the fallback system
mentioned in #82).
=> Twilio setup instructions

app/controllers/users_controller.rb, app/models/user.rb, spec/controllers/users_controller_spec.rb
#92 New users can be made now.
=> new users fixed

app/views/assignments/edit.haml
=> Keep the current user selected when editing an assignment.

app/helpers/application_helper.rb
=> Convert Ternary to Guard Clause

Gemfile, Gemfile.lock, db/seeds.rb, spec/factories/assignments.rb, spec/factories/memberships.rb, spec/factories/rosters.rb, spec/factories/users.rb, spec/spec_helper.rb, spec/system/users/index_spec.rb
Also did some cleanup in the spec_helper
=> FactoryGirl -> FactoryBot

config/deploy/production.rb
For rake tasks run by Capistrano.
=> Needed with the Upgrade to Rails 5.2 (#117)

app/controllers/assignments_controller.rb, app/views/assignments/index.haml, db/schema.rb
Passes all tests, no change in coverage.
`titleize` doesn't exactly reverse `parameterize` but since names aren't case sensitive it should be OK.
=> Parameterize Calendar URL

config/environments/test.rb, spec/features/assignments/edit_spec.rb, spec/features/assignments/index_spec.rb, spec/features/assignments/new_spec.rb, spec/models/assignment_spec.rb, spec/models/roster_spec.rb, spec/spec_helper.rb
Also added the ability to time-travel (in order to work on this)
Closes #128
=> Fix after 7 failures

Gemfile, Gemfile.lock, spec/models/assignment_spec.rb, spec/spec_helper.rb
=> Rmove mocha gem

app/assets/stylesheets/application.scss, app/assets/stylesheets/assignments/calendar.scss, app/assets/stylesheets/assignments/index.scss, app/assets/stylesheets/rosters/rosters.scss, app/views/assignments/index.haml, app/views/assignments/new.haml, app/views/assignments/rotation_generator.haml, app/views/rosters/edit.haml, app/views/rosters/index.haml, app/views/rosters/new.haml, app/views/users/edit.haml, app/views/users/index.haml, app/views/users/new.haml
=> Stop tool tips from resizing page and add padding

Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb
also Bundler version. This should take care of the deprecation warnings from Bundler
=> Upgraded capistrano, capistrano-bundler

db/migrate/20210218203357_add_uniq_indeces.rb, db/schema.rb
I was working on rubocopping the app a bit and the rails cop recommended these indeces. They're a good idea, but thought it warranted a separate PR
=> Add unique indeces where called for

app/views/assignments/index.haml, config/routes.rb
This way we don't have to construct URLs with string-interpolation and have hard-coded domains.
=> Name the ics feed route

config/initializers/content_security_policy.rb
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> Enable CSP headers

Gemfile.lock, app/models/roster.rb, app/views/sessions/dev_login.haml, spec/models/roster_spec.rb
This would have been nice when working on #171
=> Indicate admins on dev login

app/controllers/users_controller.rb, app/models/membership.rb, app/models/roster.rb, app/views/users/_form.html.haml, spec/controllers/users_controller_spec.rb, spec/factories/memberships.rb, spec/models/membership_spec.rb, spec/system/users/edit_spec.rb, spec/system/users/index_spec.rb
* Validation on `Membership`
* Errors in the flash in the controller
* Disable the checkbox too
Closes #170
=> Stop an admin from removing the only roster admin

.rspec, .rubocop.yml, spec/controllers/assignments_controller_spec.rb, spec/controllers/changes_controller_spec.rb, spec/controllers/rosters_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/twilio_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/mailers/assignments_mailer_spec.rb, spec/models/assignment_spec.rb, spec/models/roster_spec.rb, spec/models/user_spec.rb, spec/requests/assignments_controller_spec.rb, spec/system/assignment/edit_spec.rb, spec/system/assignment/index_spec.rb, spec/system/users/edit_spec.rb, spec/system/users/index_spec.rb
I enabled all of rubocop-rspec and ran through all the auto-correctable fixes.
Just 513 offenses remaining :tada:
=> Rubocop rspec (part 1)

app/views/assignments/rotation_generator.haml
Turns out that that submit button wasn't in the form. Ugh.
=> Fix rotation generator

config/environments/production.rb
=> Enable the exception-notification middeware

.travis.yml, Gemfile.lock
I'm curious to see if this will have any appreciable difference.
=> Cache `yarn` in Travis

Gemfile
=> Replace Gemfile ruby `IO.read` with `File.read`

app/models/roster.rb
Closes #263
absolute minimal adjustment needed
=> Cast dates before forwarding to `Assignment.between`

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, package.json, yarn.lock
Use `@fullcalendar/core` and the two plugins we need rather than the bundled package.
=> Fullcalendar plugins

bin/update
=> Install NPM dependencies on bin/update

.gitignore, .travis.yml, Gemfile, Gemfile.lock, app/controllers/assignments_controller.rb, app/models/assignment.rb, app/views/assignments/_current.haml, bin/setup, config/application.rb, config/application.yml.example, config/deploy.rb, config/on_call.yml, spec/controllers/assignments_controller_spec.rb, spec/mailers/assignments_mailer_spec.rb, spec/models/assignment_spec.rb
This gem is pretty old and crusty, and Rails has a built-in method for reading a single number from a yaml file.
=> Remove snappconfig gem

db/migrate/20230623172558_normalize_charsets_and_collations.rb, db/schema.rb
That way I can have a 🦖 in my last name. Very important.
=> Normalize the table encodings.

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
Was gonna fix all the forms but there's a lot of... weird stuff going on with this site, so will either look into it next week or will be told "don't bother"
=> fix error case for form submission

package.json, yarn.lock
To resolve peer dependency warnings introduced by #281
=> Updated stylelint-config-standard-scss

config/on_call.yml
Changing to 3 pm per Transit Operations
=> Change switchover time to 3 pm

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/rosters_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/roster.rb, config/initializers/friendly_id.rb, db/migrate/20230905201033_add_slug_to_rosters.rb, db/schema.rb, lib/tasks/roster_slugs.rake, spec/controllers/assignments_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/requests/assignments_controller_spec.rb, spec/requests/twilio_controller_spec.rb, spec/system/assignment/index_spec.rb
=> Add Friendly ID gem for rosters

config/application.rb, config/initializers/cookie_rotator.rb, config/initializers/new_framework_defaults_7_0.rb
=> Flipped a few more defaults

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
Merge after switch-over, scheduled 7/17
=> New signout URL

app/controllers/application_controller.rb, app/jobs/check_rosters_uncovered_dates_job.rb, app/models/assignment.rb, app/models/assignment/weekday_generator.rb, app/models/user.rb, spec/controllers/application_controller_spec.rb, spec/controllers/assignments_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/jobs/check_rosters_uncovered_dates_job_spec.rb, spec/mailers/assignments_mailer_spec.rb, spec/mailers/previews/roster_mailer_preview.rb, spec/mailers/roster_mailer_spec.rb, spec/models/assignment_spec.rb, spec/models/roster_spec.rb, spec/models/user_spec.rb, spec/requests/assignments_controller_spec.rb, spec/requests/assignments_spec.rb, spec/requests/rosters_controller_spec.rb, spec/requests/twilio_controller_spec.rb, spec/support/roster_user.rb, spec/system/assignment/edit_spec.rb, spec/system/assignment/ics_views_spec.rb, spec/system/users/index_spec.rb
Mostly: new "omit hash value" cop, a few factorybot consistencies
=> Quick pass with rubocop -a

app/views/layouts/application.html.haml
(Since I already had the code to generate the screenshot...)
Closes #421
=> Add meta viewport tag

app/controllers/users_controller.rb
Closes #294 
The select menu for adding users from another roster is now sorted by last name.
=> Sort Other Roster Select by Last Name

.overcommit.yml, Gemfile, Gemfile.lock
Adds overcommit to the repository (want to add it for @alocke8181 to use while working on some of the trainee issues here).
Config pretty much copied from round-three, with some yarn adjustments and removal of the haml-lint clause (cause we don't have haml-lint, apparently - another PR incoming for that).
=> Add overcommit

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
=> Refactor UsersController#destroy to not redirect_back

Gemfile, Gemfile.lock
=> Use ruby platform for building nokogiri

.github/workflows/ci.yml, spec/controllers/assignments_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/assignments.rb, spec/factories/users.rb, spec/requests/assignments/rotation_generator_spec.rb, spec/requests/assignments_spec.rb, spec/support/current_user.rb
And add rubocop GH action, since this gets us down to 0 offenses
=> Rubocop spec

Gemfile, Gemfile.lock, spec/spec_helper.rb
Starting to get more and more CI failures...
=> Add and configure rspec-retry

app/controllers/application_controller.rb, db/migrate/20250603145306_add_shibboleth_eppn_to_users.rb, db/schema.rb
=> Start collecting shibboleth eppn values

.github/actions/setup/action.yml, .github/dependabot.yml, .github/workflows/ci.yml
1. Added NodeJS and github-actions to Dependabot config
2. Limited token access to repository read
3. Updated outdated actions
=> Actions cleanup

.github/workflows/ci.yml, .haml-lint.yml
Also updated the checkout action while I was in here
=> Add haml-lint action

app/assets/stylesheets/application.scss
Silences sass deprecation warnings
=> Convert @import rules to @use rules
