- .rubocop.yml
- app/controllers/assignments_controller.rb
- app/controllers/twilio_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/assignments/_current.haml
- app/views/users/edit.haml
- app/views/users/index.haml
- app/views/users/new.haml
- config/locales/en.yml
- db/migrate/20151204222251_add_is_fallbackto_users.rb
- db/schema.rb
- spec/controllers/assignments_controller_spec.rb
- spec/controllers/twilio_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/models/user_spec.rb
Closes #9.
Allowing us to specify a fallback user for if if in case no one is on call.
Only one fallback user may be specified.
Incoming calls or texts are redirected to the fallback user if no one is currently on call.
The calendar shows who this is (when there's no one on call).
The users index also shows who this is.
> Fallback user

- app/controllers/users_controller.rb
- app/views/users/index.haml
- config/routes.rb
- coverage/.last_run.json
- spec/controllers/users_controller_spec.rb
> Allow adding existing users to rotations

- Gemfile
- Gemfile.lock
- config/routes.rb
Closes #81
Also, added the 'listen' gem, otherwise I couldn't check routes.
> Disable IT-fallback now that the Twilio number's set

- config/schedule.rb
Because jobapps already had this fix, and 'j' comes before 's'.
> This was _technically_ working before

- config/deploy.rb
- config/deploy/production.rb
If we use a https repo url with a public repo, then we don't need it at
all. This way we can avoid agent forwarding which has a (theoretical)
security implication.
> Don't forward SSH agent

- .travis.yml
That it should "just work" if your gemfile has the "Bundled With" line.
With the release of RubyGems 3.1, `gem update --system` also tries to
install bundler and waits for your OK before overwriting the gem binary.
> Travis insists that you dont have to

- app/views/rosters/edit.haml
@sherson noticed this today
1. It didn't have the selected value available to it, so editing a roster always selected the alphabetically first user. Fixed by using the form_for helper.
2. Fallback user is optional in the model, but there was no blank option.
> Fix fallback user select box

- Capfile
- Gemfile
- Gemfile.lock
- config/environments/production.rb
1. Rails 7 no longer automatically runs `yarn` when precompiling assets. Wasn't mentioned in the release notes, but see rails/rails#43641. Hello again, my friend, `capistrano-yarn`.
2. Uglifier was failing on a `const`... somewhere. I really have no idea where. Uglifier themselves say to use `terser` if you want ES6 support, so...
> Two fixes for compiling assets in production

- app/controllers/application_controller.rb
- app/views/sessions/subsidiary.html.haml
Closes #205.
I tried to right a request spec for this, but it turns out setting a `request.env` var is a pain. You can pass `env: { uid: 12 }` to the `get` method, but it merges that env var into the Rack env hash. That auto-prefixes it so it ends up as `HTTP_UID`.
> Check login user for subsidiary account

- app/controllers/sessions_controller.rb
I discovered today, when testing something else, that the ["Logout" link](https://github.com/umts/screaming-dinosaur/blob/7d284d9f5bd70216971e5aa162cb134da98f64e8/app/views/sessions/subsidiary.html.haml#L11) that we offer subsidiary accounts, when someone mistakenly logs in with one, didn't work because that same filter stops them from getting to `/sessions/destroy`, too.
> Allow subsidiary accounts on session routes

- app/assets/javascripts/application.js
- app/assets/javascripts/assignment.js
- app/assets/javascripts/calendar.js
- package.json
- yarn.lock
Dependabot's been complaining about this one for a while. Pretty easy given this app has ~50 lines of JS total and uses jQuery exactly 7 times. I almost considered trying to remove it, but Bootstrap 4.x still needs it.
> Upgrade jQuery to 3.x

- Gemfile
- Gemfile.lock
The internet tells me that new Selenium can manage your webdriver for you, too. This version doesn't know about the new download location for chromedriver 115 either, but it can download 114 and use that with Chrome 115.
This is an alternative to #289, and if Travis builds it successfully, I would say it's preferable.
> Switch from webdrivers to just using selenium

- config/application.rb
My _browser_ is in the EDT time zone. But in UTC it's already tomorrow. So `Time.zone.today.day` returns a different number than the calendar on the site.
Failing test locally:
https://github.com/umts/screaming-dinosaur/blob/1ba508a7fb5d812626a2ab11c5e1b36444bbf0fd/spec/system/assignment/index_spec.rb#L39-L43
> Fix test failure after 8pm

- app/views/layouts/_nav.html.haml
Only `data` and `aria` auto-expand hashes into mutliple HTML attributes. Before this fix, this made one attribute called "data-bs" with a value of `'{:toggle=&gt;&quot;collapse&quot;, :target=&gt;&quot;#navCollapse&quot;}'`.
> Fix Bootstrap data attributes on Toggler

- .overcommit.yml
Closes #440, I guess?
@benmelz, not sure what you ran into in #431, but `haml-lint` is [in the `Gemfile`](https://github.com/umts/screaming-dinosaur/blob/91918342d23c2a8544aea2b4a2bd190dbf9b724a/Gemfile#L36). This _seems_ to work OK for me?
> Add HamlLint to Overcommit

- spec/controllers/changes_controller_spec.rb
More of #423 
The `ChangesController` spec no longer uses `redirect_back`. Instead, it just checks for the `:redirected` status.
> ChangesController Spec Does Not Use Redirect_Back

- app/controllers/rosters_controller.rb
- app/views/rosters/edit.html.haml
- spec/controllers/rosters_controller_spec.rb
Continuation of #423 
Removed all occurrences of `redirect_back` and `report_errors` from `RosterController` and the specs. `create` and `update` now re-render `:new` and `:edit` on failure with an `:uprocessable_entity` status. The specs that checked for a `redirect_back` now look for that status.
I noticed that `destroy` does not have any checks for errors besides `require_admin_in_roster`. All the other controllers have some form of a catch for errors when destroying. I'll create a small PR and add it after this one.
> Removed All Occurrences of redirect_back and report_errors from RosterController

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- spec/spec_helper.rb
Closes #423 
Removed `umts-custom-matchers` from the `Gemfile` and `spec_helper`. Also removed `ApplicationController#report_errors` since that was no longer used.
> Removed umts-custom-matchers Gem and ApplicationController#report_errors

- config/deploy/production.rb
We're _not_ building Nokogiri, and in this case, we _could_ with system libraries because Ubuntu has slightly newer libxml2. But, we definitely don't need to.
> Don't use system libraries to build Nokogiri

- .rubocop.yml
- Gemfile.lock
And move them to `plugins:` in the config
> Upgrade remaining plugin-able rubocop gems

- contrib/am-eve-split/package-lock.json
- contrib/am-eve-split/package.json
The versions of `@twilio/runtime-handler` and `twilio` that are available are determined by the serverless environment, not NPM. The available runtime-handler versions are here:
https://www.twilio.com/docs/serverless/functions-assets/handler
The available versions of twilio are a mystery - some of them just won't work. So, I changed the dependency to be the same as runtime-handler's.
> Update Twilio NPM packages

- app/controllers/assignments_controller.rb
@sherson asks for an "Admin CSV" in August of 2023 (#299), gets it. Then Matt breaks it 1 week later (#308) - remains broken for two years.
> Fix CSV export when using friendly-id slugged ids
